-- Phase 4 — subscription / billing support.
--
-- Additive and safe: does NOT change hub_dataset or any public access. Stripe + subscription
-- state lives on the profile (server-written only); billing_events is an append-only audit
-- log of every processed Stripe event, keyed by Stripe's event id for idempotency.

-- ── profiles: subscription / Stripe columns ─────────────────────────────────────────────
alter table public.profiles
  add column if not exists subscription_status               text not null default 'free',
  add column if not exists stripe_customer_id                text,
  add column if not exists stripe_subscription_id            text,
  add column if not exists subscription_current_period_end   timestamptz,
  add column if not exists subscription_cancel_at_period_end boolean not null default false;

-- Unique (but nullable) Stripe identifiers, as partial unique indexes so re-runs are safe
-- and many free users (all NULL) don't collide.
create unique index if not exists profiles_stripe_customer_id_key
  on public.profiles (stripe_customer_id) where stripe_customer_id is not null;
create unique index if not exists profiles_stripe_subscription_id_key
  on public.profiles (stripe_subscription_id) where stripe_subscription_id is not null;

-- NOTE: these columns are SERVER-controlled (Stripe webhook via the service role). The
-- authenticated column-grant from 0002 is an allow-list that does NOT include them, so a
-- client still cannot change subscription_status / stripe_* / period_end / cancel flag.
-- We intentionally add NO new grant here.

-- ── billing_events: append-only Stripe event log ────────────────────────────────────────
create table if not exists public.billing_events (
  id                     bigint generated by default as identity primary key,
  profile_id             uuid references public.profiles(id) on delete set null,
  stripe_customer_id     text,
  stripe_subscription_id text,
  event_type             text not null,
  event_id               text unique,         -- Stripe event id → idempotency key
  payload                jsonb not null,
  created_at             timestamptz not null default now()
);

create index if not exists billing_events_profile_id_idx on public.billing_events (profile_id);
create index if not exists billing_events_customer_idx    on public.billing_events (stripe_customer_id);

alter table public.billing_events enable row level security;

-- Locked down. anon/authenticated get no direct access; only the service role (server-side
-- Pages Functions) writes/reads it (service_role bypasses RLS). An OPTIONAL admin-only read
-- policy is provided for internal dashboards: visible only to profiles.role = 'admin'.
revoke all on public.billing_events from anon, authenticated;
grant all on public.billing_events to service_role;

grant select on public.billing_events to authenticated;  -- gated to admins by the policy below
drop policy if exists "billing_events_admin_select" on public.billing_events;
create policy "billing_events_admin_select"
  on public.billing_events
  for select
  to authenticated
  using ( (select p.role from public.profiles p where p.id = auth.uid()) = 'admin' );

-- ── TODO (Phase 5) ──────────────────────────────────────────────────────────────────────
-- Gate hub_dataset on subscription_status (e.g. premium tabs require 'active'); until then
-- hub_dataset stays public-read so the dashboard keeps working with no login.
